# Generated by Django 4.0.2 on 2022-07-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0035_alter_project_taskassign_workaccept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_taskassign',
            name='workaccept',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
