# Generated by Django 4.0.2 on 2022-08-11 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0039_project_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_taskassign',
            name='projectphase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_taskassignprojectphase', to='base_app.project_phase'),
        ),
    ]
